const DEFAULT_APP='';
chrome.storage.local.get('libraryOrigin').then(s=>{document.getElementById('library').value=s.libraryOrigin||DEFAULT_APP;});
let tab,blocked=false;
const capture=document.getElementById('capture'),status=document.getElementById('status');
(async()=>{try{[tab]=await chrome.tabs.query({active:true,currentWindow:true});if(!/^https?:\/\//.test(tab.url||''))throw new Error('Bitte eine normale Website öffnen. Browser-interne Seiten können nicht geclippt werden.');document.getElementById('source').textContent=new URL(tab.url).hostname;const [res]=await chrome.scripting.executeScript({target:{tabId:tab.id},func:()=>Array.from(document.querySelectorAll('input[type=password]')).some(el=>el.getClientRects().length>0)});blocked=!!res.result;document.getElementById('login').hidden=!blocked;if(blocked)status.textContent='Bitte erst auf der Website anmelden.';}catch(e){status.textContent=e.message;blocked=true;}})();
document.getElementById('confirmed').addEventListener('change',e=>{capture.disabled=!e.target.checked||blocked;});
capture.addEventListener('click',async()=>{capture.disabled=true;status.textContent='Inhalt wird erfasst …';try{const app=new URL(document.getElementById('library').value);if(app.protocol!=='https:'&&!(app.protocol==='http:'&&['localhost','127.0.0.1'].includes(app.hostname)))throw new Error('Bitte eure HTTPS-Bibliotheksadresse eingeben.');if(app.username||app.password||app.pathname!=='/')throw new Error('Bitte nur die Bibliotheksadresse ohne Unterordner eingeben.');const matches=[app.origin+'/*'];const granted=await chrome.permissions.request({origins:matches});if(!granted)throw new Error('Die Berechtigung für eure Bibliothek wird zur Clip-Übergabe benötigt.');const previous=await chrome.scripting.getRegisteredContentScripts({ids:['ablage-bridge']});if(previous.length)await chrome.scripting.unregisterContentScripts({ids:['ablage-bridge']});await chrome.scripting.registerContentScripts([{id:'ablage-bridge',matches,js:['bridge.js'],runAt:'document_idle',persistAcrossSessions:true}]);await chrome.storage.local.set({libraryOrigin:app.origin});const type=document.getElementById('type').value;const [result]=await chrome.scripting.executeScript({target:{tabId:tab.id},args:[type],func:(type)=>{
const url=location.href,title=document.title,selection=getSelection()?.toString().trim();
if(type==='link')return{url,title,type,content:'',note:'',archive:''};
const root=type==='article'?(document.querySelector('article')||document.querySelector('main')||document.body):document.body;
const tags=new Set(['P','DIV','SECTION','ARTICLE','MAIN','HEADER','FOOTER','NAV','ASIDE','H1','H2','H3','H4','H5','H6','UL','OL','LI','BLOCKQUOTE','PRE','CODE','TABLE','THEAD','TBODY','TR','TH','TD','STRONG','EM','B','I','SPAN','BR','HR','FIGURE','FIGCAPTION']);
const drop=new Set(['SCRIPT','STYLE','NOSCRIPT','IFRAME','OBJECT','EMBED','FORM','INPUT','TEXTAREA','SELECT','BUTTON','META','LINK','TEMPLATE','SVG','CANVAS','VIDEO','AUDIO']);
let total=0;
function clone(node){if(++total>40000)return document.createTextNode('');if(node.nodeType===Node.TEXT_NODE)return document.createTextNode(node.textContent||'');if(node.nodeType!==Node.ELEMENT_NODE)return document.createTextNode('');if(drop.has(node.tagName)||node.hidden||node.getAttribute('aria-hidden')==='true')return document.createTextNode('');const css=getComputedStyle(node);if(css.display==='none'||css.visibility==='hidden')return document.createTextNode('');if(node.tagName==='IMG'){try{if(node.complete&&node.naturalWidth>40){const canvas=document.createElement('canvas');const scale=Math.min(1,1000/node.naturalWidth);canvas.width=node.naturalWidth*scale;canvas.height=node.naturalHeight*scale;if(canvas.width*canvas.height>1500000)return document.createTextNode(node.alt||'');canvas.getContext('2d').drawImage(node,0,0,canvas.width,canvas.height);const img=document.createElement('img');img.src=canvas.toDataURL('image/jpeg',.7);img.alt=node.alt||'';return img;}}catch{}return document.createTextNode(node.alt?'[Bild: '+node.alt+']':'');}const el=document.createElement(tags.has(node.tagName)?node.tagName.toLowerCase():'span');for(const child of node.childNodes)el.appendChild(clone(child));return el;}
const copy=clone(root),content=type==='article'&&selection?selection:root.innerText;const archive=type==='page'||(!selection&&copy.querySelector?.('img'))?copy.outerHTML:'';
return{url,title,type,content:content.slice(0,1000000),note:'',archive:archive.length<=5000000?archive:''};
}});const clip=result.result;if(!clip?.content&&type!=='link')throw new Error('Kein lesbarer Inhalt gefunden. Bitte zuerst anmelden oder eine Textstelle markieren.');const id=crypto.randomUUID();await chrome.storage.local.set({['capture:'+id]:{clip,createdAt:Date.now()}});await chrome.tabs.create({url:app.origin+'/?capture='+id});window.close();}catch(e){status.textContent=(e instanceof TypeError?'Bitte zuerst eure Bibliotheksadresse eintragen.':e.message)||'Erfassung nicht möglich. Bitte den Inhalt manuell in Die ABLAGE einfügen.';capture.disabled=false;}});
