const DEFAULT_APP='https://ablage.partei-hildesheim.de';
chrome.storage.local.get('libraryOrigin').then(s=>{document.getElementById('library').value=s.libraryOrigin||DEFAULT_APP;});
let tab,blocked=false;
const capture=document.getElementById('capture'),status=document.getElementById('status');
(async()=>{try{[tab]=await chrome.tabs.query({active:true,currentWindow:true});if(!/^https?:\/\//.test(tab.url||''))throw new Error('Bitte eine normale Website öffnen. Browser-interne Seiten können nicht geclippt werden.');document.getElementById('source').textContent=new URL(tab.url).hostname;const [res]=await chrome.scripting.executeScript({target:{tabId:tab.id},func:()=>Array.from(document.querySelectorAll('input[type=password]')).some(el=>el.getClientRects().length>0)});const loginVisible=!!res.result;blocked=false;document.getElementById('login').hidden=!loginVisible;if(loginVisible)status.textContent='Bitte erst auf der Website anmelden.';}catch(e){status.textContent=e.message;blocked=true;}})();
document.getElementById('confirmed').addEventListener('change',e=>{capture.disabled=!e.target.checked||blocked;});
capture.addEventListener('click',async()=>{capture.disabled=true;status.textContent='Inhalt wird erfasst …';try{const app=new URL(document.getElementById('library').value);if(app.protocol!=='https:'&&!(app.protocol==='http:'&&['localhost','127.0.0.1'].includes(app.hostname)))throw new Error('Bitte eure HTTPS-Bibliotheksadresse eingeben.');if(app.username||app.password||app.pathname!=='/')throw new Error('Bitte nur die Bibliotheksadresse ohne Unterordner eingeben.');const matches=[app.origin+'/*'];const granted=await chrome.permissions.request({origins:matches});if(!granted)throw new Error('Die Berechtigung für eure Bibliothek wird zur Clip-Übergabe benötigt.');const previous=await chrome.scripting.getRegisteredContentScripts({ids:['ablage-bridge']});if(previous.length)await chrome.scripting.unregisterContentScripts({ids:['ablage-bridge']});await chrome.scripting.registerContentScripts([{id:'ablage-bridge',matches,js:['bridge.js'],runAt:'document_idle',persistAcrossSessions:true}]);await chrome.storage.local.set({libraryOrigin:app.origin});const type=document.getElementById('type').value;if(type==='screenshot'){const [current]=await chrome.tabs.query({active:true,windowId:tab.windowId});if(current?.id!==tab.id)throw Error('Die aktive Seite hat gewechselt. Öffne den Clipper erneut auf der gewünschten Quelle.');const image=await chrome.tabs.captureVisibleTab(tab.windowId,{format:'png'});const id=crypto.randomUUID();await chrome.storage.local.set({['shot:'+id]:{image,url:tab.url,title:tab.title||'Screenshot',createdAt:Date.now()}});await chrome.tabs.create({url:chrome.runtime.getURL('screenshot.html?id='+id)});window.close();return;}await chrome.scripting.executeScript({target:{tabId:tab.id},files:['capture.js']});
if(type==='regions'){await chrome.scripting.executeScript({target:{tabId:tab.id},files:['region-picker.js']});window.close();return;}
const [result]=await chrome.scripting.executeScript({target:{tabId:tab.id},args:[type],func:type=>globalThis.AblageCapture.capture(type)});const clip=result.result;if(!clip?.content&&type!=='link')throw new Error('Kein lesbarer Inhalt gefunden. Bitte zuerst anmelden oder eine Textstelle markieren.');const id=await AblageQueue.save(clip);await chrome.tabs.create({url:app.origin+'/?capture='+id});window.close();}catch(e){status.textContent=(e instanceof TypeError?'Bitte zuerst eure Bibliotheksadresse eintragen.':e.message)||'Erfassung nicht möglich. Bitte den Inhalt manuell in Die ABLAGE einfügen.';capture.disabled=!document.getElementById('confirmed').checked||blocked;}});

document.getElementById('type').addEventListener('change',e=>{const regions=e.target.value==='regions';capture.textContent=regions?'Bereiche auswählen':'In Die ABLAGE prüfen';document.getElementById('region-hint').hidden=!regions;});

(async()=>{await AblageQueue.prune();const all=await chrome.storage.local.get(null);const entries=Object.entries(all).filter(([key])=>key.startsWith('capture:')).sort((a,b)=>b[1].createdAt-a[1].createdAt);const list=document.getElementById('drafts');for(const [key,pending] of entries){const row=document.createElement('div');row.className='draft-row';const open=document.createElement('button');open.className='secondary';open.textContent=pending.clip.title||'Entwurf öffnen';open.onclick=async()=>{try{const origin=(await chrome.storage.local.get('libraryOrigin')).libraryOrigin||DEFAULT_APP;await chrome.tabs.create({url:origin+'/?capture='+key.slice(8)});}catch{status.textContent='Entwurf konnte nicht geöffnet werden. Prüfe die Bibliotheksadresse.';}};const discard=document.createElement('button');discard.className='secondary';discard.textContent='Verwerfen';discard.onclick=async()=>{if(discard.dataset.confirm!=='yes'){discard.dataset.confirm='yes';discard.textContent='Bestätigen';return;}await chrome.storage.local.remove(key);row.remove();};row.append(open,discard);list.append(row);}document.getElementById('draft-section').hidden=!entries.length;})().catch(()=>{status.textContent='Entwürfe konnten nicht geladen werden.';});
