const DEFAULT_APP='https://ablage.partei-hildesheim.de';
chrome.storage.local.get('libraryOrigin').then(s=>{document.getElementById('library').value=s.libraryOrigin||DEFAULT_APP;});
let tab,blocked=false;
const capture=document.getElementById('capture'),status=document.getElementById('status');
(async()=>{try{[tab]=await chrome.tabs.query({active:true,currentWindow:true});if(!/^https?:\/\//.test(tab.url||''))throw new Error('Bitte eine normale Website öffnen. Browser-interne Seiten können nicht geclippt werden.');document.getElementById('source').textContent=new URL(tab.url).hostname;const [res]=await chrome.scripting.executeScript({target:{tabId:tab.id},func:()=>Array.from(document.querySelectorAll('input[type=password]')).some(el=>el.getClientRects().length>0)});blocked=!!res.result;document.getElementById('login').hidden=!blocked;if(blocked)status.textContent='Bitte erst auf der Website anmelden.';}catch(e){status.textContent=e.message;blocked=true;}})();
document.getElementById('confirmed').addEventListener('change',e=>{capture.disabled=!e.target.checked||blocked;});
capture.addEventListener('click',async()=>{capture.disabled=true;status.textContent='Inhalt wird erfasst …';try{const app=new URL(document.getElementById('library').value);if(app.protocol!=='https:'&&!(app.protocol==='http:'&&['localhost','127.0.0.1'].includes(app.hostname)))throw new Error('Bitte eure HTTPS-Bibliotheksadresse eingeben.');if(app.username||app.password||app.pathname!=='/')throw new Error('Bitte nur die Bibliotheksadresse ohne Unterordner eingeben.');const matches=[app.origin+'/*'];const granted=await chrome.permissions.request({origins:matches});if(!granted)throw new Error('Die Berechtigung für eure Bibliothek wird zur Clip-Übergabe benötigt.');const previous=await chrome.scripting.getRegisteredContentScripts({ids:['ablage-bridge']});if(previous.length)await chrome.scripting.unregisterContentScripts({ids:['ablage-bridge']});await chrome.scripting.registerContentScripts([{id:'ablage-bridge',matches,js:['bridge.js'],runAt:'document_idle',persistAcrossSessions:true}]);await chrome.storage.local.set({libraryOrigin:app.origin});const type=document.getElementById('type').value;await chrome.scripting.executeScript({target:{tabId:tab.id},files:['capture.js']});
if(type==='regions'){await chrome.scripting.executeScript({target:{tabId:tab.id},files:['region-picker.js']});window.close();return;}
const [result]=await chrome.scripting.executeScript({target:{tabId:tab.id},args:[type],func:type=>globalThis.AblageCapture.capture(type)});const clip=result.result;if(!clip?.content&&type!=='link')throw new Error('Kein lesbarer Inhalt gefunden. Bitte zuerst anmelden oder eine Textstelle markieren.');const id=crypto.randomUUID();await chrome.storage.local.set({['capture:'+id]:{clip,createdAt:Date.now()}});await chrome.tabs.create({url:app.origin+'/?capture='+id});window.close();}catch(e){status.textContent=(e instanceof TypeError?'Bitte zuerst eure Bibliotheksadresse eintragen.':e.message)||'Erfassung nicht möglich. Bitte den Inhalt manuell in Die ABLAGE einfügen.';capture.disabled=false;}});

document.getElementById('type').addEventListener('change',e=>{const regions=e.target.value==='regions';capture.textContent=regions?'Bereiche auswählen':'In Die ABLAGE prüfen';document.getElementById('region-hint').hidden=!regions;});
