(()=>{
 globalThis.AblagePicker?.close();
 const previousFocus=document.activeElement,selected=new Set(),host=document.createElement('div');host.dataset.ablagePicker='';host.style.cssText='all:initial;position:fixed;inset:0;pointer-events:none;z-index:2147483647';
 const shadow=host.attachShadow({mode:'closed'}),style=document.createElement('style');
 style.textContent=`@font-face{font-family:Barlow;src:url(${chrome.runtime.getURL('fonts/barlow-400.woff2')});font-weight:400}@font-face{font-family:Barlow;src:url(${chrome.runtime.getURL('fonts/barlow-600.woff2')});font-weight:600}@font-face{font-family:BarlowCondensed;src:url(${chrome.runtime.getURL('fonts/barlow-condensed-700.woff2')});font-weight:700}:host{color-scheme:light}*{box-sizing:border-box} .panel{position:absolute;bottom:20px;right:20px;width:min(460px,calc(100vw - 40px));max-height:calc(100dvh - 40px);overflow:auto;pointer-events:auto;background:#f4f4f2;color:#202022;padding:20px;border-radius:4px;box-shadow:0 12px 40px #20202233;font:16px/1.5 Barlow,sans-serif}h2{font-family:BarlowCondensed,sans-serif;font-weight:700;font-size:28px;line-height:1.2;margin:0 0 10px}p{margin:8px 0} .muted{color:#626265;font-size:14px}.actions{display:flex;flex-wrap:wrap;gap:8px;margin-top:14px}button{font:600 14px/1.3 Barlow,sans-serif;min-height:44px;padding:10px 12px;background:#fff;color:#202022;border:1px solid #cececb;border-radius:4px;cursor:pointer}button:hover{background:#eeeee9}button:focus-visible{outline:3px solid #b31229;outline-offset:3px}button:disabled{opacity:.5;cursor:not-allowed}.primary{background:#b31229;color:white;border-color:#b31229}.primary:hover{background:#961225}.box{position:absolute;pointer-events:none;border:2px solid #b31229;background:#b3122914}.hover{border-style:dashed;background:transparent}.preview{max-height:240px;overflow:auto;margin-top:12px;padding:16px;background:#fff;font:16px/1.7 Georgia,serif;overflow-wrap:anywhere}.preview img{max-width:100%;height:auto}.preview table{display:block;overflow:auto}.preview pre{white-space:pre-wrap}.error{color:#961225}.preview[hidden]{display:none}::selection{background:#f6c8cf;color:#621220}`;
 shadow.append(style);const marks=document.createElement('div'),panel=document.createElement('section');panel.className='panel';panel.setAttribute('aria-label','Die ABLAGE Bereichsauswahl');panel.innerHTML='<h2>Bereiche auswählen</h2><p class="muted">Absatz, Bild oder Tabelle anklicken. Erneutes Anklicken entfernt den Bereich. Scrollen bleibt möglich.</p><p id="count" role="status" aria-live="polite">Noch kein Bereich ausgewählt.</p><div class="actions"><button id="previous" aria-label="Vorherigen Bereich hervorheben">Vorheriger Bereich</button><button id="next">Nächster Bereich</button><button id="toggle" disabled>Bereich übernehmen</button></div><div id="preview" class="preview" hidden></div><p id="error" class="error" role="alert"></p><div class="actions"><button id="review" disabled>Auswahl prüfen</button><button id="send" class="primary" hidden>In Die ABLAGE prüfen</button><button id="reset" disabled>Auswahl leeren</button><button id="close">Abbrechen</button></div><p class="muted">Escape beendet die Auswahl. Die Bereiche werden in Seitenreihenfolge übernommen. Eingabefelder und eingebettete Frames werden ausgelassen.</p>';
 shadow.append(marks,panel);document.documentElement.appendChild(host);
 const $=id=>shadow.getElementById(id);let hover=null,frame=0,busy=false,reviewed=null;
 function eligible(el){return el instanceof HTMLElement&&!host.contains(el)&&!el.closest('[data-ablage-picker],form,input,textarea,select,button,[contenteditable],iframe')&&el.getClientRects().length&&getComputedStyle(el).visibility!=='hidden';}
 function target(el){if(!(el instanceof Element))return null;const leaf=el.closest('table,figure,blockquote,pre,p,h1,h2,h3,h4,h5,h6,li,img');if(leaf&&eligible(leaf))return leaf;const block=el.closest('div,section,article,main');return block&&eligible(block)&&block.innerText.trim()?block:null;}
 function roots(){return [...selected].filter(el=>el.isConnected).sort((a,b)=>a.compareDocumentPosition(b)&Node.DOCUMENT_POSITION_FOLLOWING?-1:1);}
 function draw(){frame=0;marks.replaceChildren();for(const el of [...selected,hover].filter(Boolean)){if(!el.isConnected)continue;const rect=el.getBoundingClientRect();if(rect.bottom<0||rect.top>innerHeight)continue;const box=document.createElement('div');box.className='box'+(!selected.has(el)?' hover':'');box.style.cssText=`left:${rect.left}px;top:${rect.top}px;width:${rect.width}px;height:${rect.height}px`;marks.appendChild(box);}}
 function schedule(){if(!frame)frame=requestAnimationFrame(draw);}
 function update(){reviewed=null;$('preview').hidden=true;$('preview').replaceChildren();$('send').hidden=true;$('review').hidden=false;$('review').disabled=!selected.size;$('reset').disabled=!selected.size;$('count').textContent=selected.size?`${selected.size} ${selected.size===1?'Bereich ausgewählt':'Bereiche ausgewählt'}.`:'Noch kein Bereich ausgewählt.';$('error').textContent='';schedule();}
 function setHover(el){hover=el;$('toggle').disabled=!el||busy;$('toggle').textContent=selected.has(el)?'Bereich entfernen':'Bereich übernehmen';schedule();}
 function toggle(el){if(!el||busy)return;if(selected.has(el))selected.delete(el);else{if(selected.size>=50){$('error').textContent='Maximal 50 Bereiche. Bitte zunächst einen Bereich entfernen.';return;}for(const current of [...selected]){if(current.contains(el))selected.delete(current);else if(el.contains(current))selected.delete(current);}selected.add(el);}update();setHover(el);}
 function move(event){if(event.composedPath().includes(host)||busy)return;setHover(target(event.target));}
 function click(event){if(event.composedPath().includes(host))return;event.preventDefault();event.stopImmediatePropagation();if(!busy)toggle(target(event.target));}
 function key(event){if(event.key==='Escape'&&!busy){event.preventDefault();event.stopImmediatePropagation();close();}}
 function cycle(direction){const candidates=[...document.querySelectorAll('p,h1,h2,h3,h4,h5,h6,table,figure,blockquote,pre,li,img')].filter(eligible).filter(el=>!el.closest('table,figure,blockquote,pre,li')||el.closest('table,figure,blockquote,pre,li')===el);if(!candidates.length){$('error').textContent='Keine auswählbaren Bereiche gefunden. Nutze die Textauswahl in der Erweiterung.';return;}let index=candidates.indexOf(hover);index=(index+direction+candidates.length)%candidates.length;setHover(candidates[index]);hover.scrollIntoView({block:'center',behavior:'auto'});$('count').textContent=`${selected.size} ausgewählt. Hervorgehoben: ${hover.tagName==='IMG'?'Bild':hover.innerText.trim().slice(0,100)||hover.tagName}.`;}
 function close(){document.removeEventListener('pointermove',move,true);document.removeEventListener('click',click,true);document.removeEventListener('keydown',key,true);document.removeEventListener('scroll',schedule,true);window.removeEventListener('resize',schedule);if(frame)cancelAnimationFrame(frame);host.remove();if(previousFocus?.isConnected)previousFocus.focus({preventScroll:true});delete globalThis.AblagePicker;}
 $('previous').onclick=()=>cycle(-1);$('next').onclick=()=>cycle(1);$('toggle').onclick=()=>toggle(hover);$('close').onclick=close;$('reset').onclick=()=>{selected.clear();update();};
 $('review').onclick=()=>{try{if(roots().length!==selected.size)throw Error('Ein Bereich ist nicht mehr auf der Seite. Bitte die Auswahl leeren und erneut auswählen.');reviewed=globalThis.AblageCapture.capture('article',roots());if(!reviewed.content.trim()&&!reviewed.archive.includes('<img'))throw Error('Die Auswahl enthält keinen lesbaren Inhalt. Bitte andere Bereiche auswählen.');const template=document.createElement('template');template.innerHTML=reviewed.archive;$('preview').replaceChildren(template.content);$('preview').hidden=false;$('review').hidden=true;$('send').hidden=false;$('error').textContent='';$('send').focus();}catch(error){$('error').textContent=error.message;}};
 $('send').onclick=async()=>{if(!reviewed||busy)return;busy=true;for(const button of panel.querySelectorAll('button'))button.disabled=true;$('send').textContent='Auswahl wird übergeben …';try{const result=await chrome.runtime.sendMessage({action:'ablage-region-capture',clip:reviewed});if(!result?.ok)throw Error(result?.error||'Übergabe fehlgeschlagen. Bitte erneut versuchen.');close();}catch(error){busy=false;for(const button of panel.querySelectorAll('button'))button.disabled=false;$('send').textContent='In Die ABLAGE prüfen';$('error').textContent=error.message;setHover(hover);}};
 document.addEventListener('pointermove',move,true);document.addEventListener('click',click,true);document.addEventListener('keydown',key,true);document.addEventListener('scroll',schedule,true);window.addEventListener('resize',schedule);globalThis.AblagePicker={close};$('next').focus();
})();
