import {useState} from 'react';
import {Search, X, Check, Download} from 'lucide-react';
export function SavedSearches({items,apply,remove}:{items:any[];apply:(p:any)=>void;remove:(id:string)=>void}){
 return items.length>0?<details className="saved-searches"><summary>Meine gespeicherten Suchen · {items.length}</summary><ul>{items.map(s=><li key={s.id}><button className="text-btn" onClick={()=>apply(s.params)}><Search size={16}/>{s.name}</button><button className="icon-btn" aria-label={`Suche „${s.name}“ entfernen`} onClick={()=>remove(s.id)}><X size={16}/></button></li>)}</ul></details>:null;
}
export function SaveSearch({save,busy}:{save:(name:string)=>Promise<any>;busy:boolean}){
 const [open,setOpen]=useState(false),[name,setName]=useState('');
 return open?<form className="save-search-form" onSubmit={async e=>{e.preventDefault();if(await save(name)){setOpen(false);setName('');}}}><label>Suchname<input autoFocus required maxLength={100} value={name} placeholder="z. B. Bahnhof – PDFs" onChange={e=>setName(e.target.value)}/></label><button className="secondary" disabled={busy}><Check size={16}/>Speichern</button><button type="button" className="text-btn" onClick={()=>setOpen(false)}>Abbrechen</button><small>Nur für dich · Suchbegriffe und alle aktuellen Filter werden gespeichert.</small></form>:<button className="text-btn" onClick={()=>setOpen(true)}><Search size={16}/>Suche speichern</button>;
}
export function BulkTools({count,collections,apply,busy,shared}:{count:number;collections:any[];apply:(p:any)=>Promise<any>;busy:boolean;shared:boolean}){
 const [op,setOp]=useState('collection'),[collection,setCollection]=useState(''),[tags,setTags]=useState('');
 return <form className="bulk-tools" onSubmit={async e=>{e.preventDefault();await apply({operation:op,collectionId:collection,tags:tags.split(',').map(t=>t.trim()).filter(Boolean)});}}><strong>{count} ausgewählt</strong><label>Aktion<select value={op} onChange={e=>setOp(e.target.value)}><option value="collection">Sammlung ändern</option><option value="tags">Tags ergänzen</option></select></label>{op==='collection'?<label>Sammlung<select value={collection} onChange={e=>setCollection(e.target.value)}><option value="">Ohne Sammlung</option>{collections.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>:<label>Tags<input value={tags} placeholder="Mit Kommas trennen" onChange={e=>setTags(e.target.value)}/></label>}<button className="primary" disabled={busy||!count||(op==='tags'&&!tags.trim())}>Auf Auswahl anwenden</button>{op==='collection'&&shared&&<p>Ein Sammlungswechsel kann den Zugriff über bestehende Sammlungslinks ändern. Prüfe die Zielsammlung.</p>}{op==='collection'&&collections.find(c=>c.id===collection)?.shared&&<p>Die Zielsammlung ist geteilt. Die ausgewählten Clips werden über ihre Leselinks sichtbar.</p>}</form>;
}
export function DuplicateNotice({items,allow,onAllow,open}:{items:any[];allow:boolean;onAllow:(v:boolean)=>void;open:(c:any)=>void}){
 return items.length>0?<section className="duplicate-notice" aria-label="Bereits gespeicherte Quelle"><h3>Diese Quelle ist bereits abgelegt.</h3><ul>{items.map(c=><li key={c.id}><button className="text-btn" onClick={()=>open(c)}>{c.title}</button></li>)}</ul><label className="check-label"><input type="checkbox" checked={allow} onChange={e=>onAllow(e.target.checked)}/>Trotzdem eine weitere Kopie speichern</label></section>:null;
}
export function ExportButton({download,busy}:{download:()=>void;busy:boolean}){return <button className="secondary" disabled={busy} onClick={download}><Download size={16}/>{busy?'Export wird erstellt …':'Sammlung exportieren'}</button>;}
