import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import Workspace from './workspace';
import SharedReader from './shared-reader';
import Brand from './brand';
import './style.css';
function App(){const [session,setSession]=useState<any>(null),[shared,setShared]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);const parts=location.pathname.split('/'),token=parts[2]||'',invite=parts[1]==='invite',publicRead=parts[1]==='s';
useEffect(()=>{fetch(publicRead?'/api/share?token='+encodeURIComponent(token):'/api/auth',{cache:'no-store'}).then(async r=>{const j=await r.json();if(!r.ok)throw Error(j.error);if(publicRead)setShared(j);else setSession(j);}).catch(e=>setError(e.message));},[]);
async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');const f=new FormData(e.currentTarget);try{const r=await fetch('/api/auth',{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':session?.csrf||''},body:JSON.stringify({action:invite?'accept':'login',token,email:f.get('email'),password:f.get('password'),name:f.get('name')})});const j=await r.json();if(!r.ok)throw Error(j.error);location.assign('/'+location.search);}catch(e){setError((e as Error).message);setBusy(false);}}
if(publicRead)return shared?<SharedReader token={token} title={shared.title} clips={shared.clips}/>:<main className="signin"><Brand/><h1>{error?'Dieser Leselink ist nicht verfügbar.':'Inhalte werden geladen …'}</h1>{error&&<><p role="alert">{error}</p><button className="secondary" onClick={()=>location.reload()}>Erneut versuchen</button></>}<a href="/">Zur Bibliothek</a></main>;
if(session?.user&&!invite)return <Workspace/>;
return <main className="signin"><Brand/><h1>{invite?'Willkommen in der ABLAGE.':<>Wissen ist Macht.<br/>Ablage auch.</>}</h1><p>{invite?'Lege deinen Namen und dein Passwort fest, um dem Team beizutreten.':'Webinhalte sammeln, in Ruhe lesen und gezielt mit deinem Team teilen.'}</p>{error&&<div className="error" role="alert">{error}{!session&&<button className="secondary" onClick={()=>location.reload()}>Erneut versuchen</button>}</div>}{session?<form onSubmit={submit}>{invite?<label className="field">Dein Name<input name="name" required maxLength={100} autoComplete="name"/></label>:<label className="field">E-Mail-Adresse<input name="email" required type="email" autoComplete="username"/></label>}<label className="field">{invite?'Neues Passwort':'Passwort'}<input name="password" required type="password" minLength={invite?12:1} maxLength={1024} autoComplete={invite?'new-password':'current-password'}/>{invite&&<span>Mindestens 12 Zeichen. Ein langes Passwort aus mehreren Wörtern funktioniert gut.</span>}</label><button className="primary" disabled={busy}>{busy?'Wird geprüft …':invite?'Team beitreten':'Anmelden'}</button></form>:!error&&<p role="status">Anmeldung wird geladen …</p>}<p className="muted">Die Bibliothek ist nur für eingeladene Teammitglieder sichtbar. Geheime Leselinks funktionieren ohne Anmeldung.</p></main>;
}createRoot(document.getElementById('root')!).render(<App/>);
