import {useEffect,useState} from 'react';
import {useEditor,EditorContent} from '@tiptap/react';
import StarterKit from '@tiptap/starter-kit';
import {Markdown} from '@tiptap/markdown';
import {Bold,Italic,List,ListOrdered,Quote,Link,Undo,Redo} from 'lucide-react';
export default function NoteEditor({value,onChange,label='Eigene Notiz',readOnly=false}:{value:string;onChange:(v:string)=>void;label?:string;readOnly?:boolean}){
 const [source,setSource]=useState(false),[linkOpen,setLinkOpen]=useState(false),[url,setUrl]=useState('');const [revision,setRevision]=useState(0);
 const unsupported=/^\s*\|.*\|\s*$|!\[[^\]]*\]\(|^\s*[-*+] \[[ xX]\]|<\/?[a-z]/m.test(value);
 const editor=useEditor({extensions:[StarterKit.configure({heading:{levels:[2,3]},link:{openOnClick:false,autolink:false}}),Markdown],content:value,contentType:'markdown',editable:!readOnly,editorProps:{attributes:{role:'textbox','aria-label':label,'aria-multiline':'true'}},onUpdate:({editor})=>onChange(editor.getMarkdown()),onSelectionUpdate:()=>setRevision(v=>v+1)});
 useEffect(()=>{if(editor&&editor.getMarkdown()!==value)editor.commands.setContent(value,{contentType:'markdown',emitUpdate:false});},[editor,value]);useEffect(()=>{editor?.setEditable(!readOnly);},[editor,readOnly]);
 if(readOnly)return null;
 const tools=[['Fett',Bold,'bold',()=>editor?.chain().focus().toggleBold().run()],['Kursiv',Italic,'italic',()=>editor?.chain().focus().toggleItalic().run()],['Aufzählung',List,'bulletList',()=>editor?.chain().focus().toggleBulletList().run()],['Nummerierte Liste',ListOrdered,'orderedList',()=>editor?.chain().focus().toggleOrderedList().run()],['Zitat',Quote,'blockquote',()=>editor?.chain().focus().toggleBlockquote().run()]] as const;
 return <div className="markdown-editor" data-revision={revision}><div className="editor-mode"><strong>{label}</strong><button type="button" className="text-btn" aria-pressed={source||unsupported} onClick={()=>setSource(!source)} disabled={unsupported}>{unsupported?'Markdown-Quelltext':source?'Visuell bearbeiten':'Markdown-Quelltext'}</button></div>{unsupported&&<p className="editor-hint">Diese Notiz enthält Tabellen, Bilder, Aufgaben oder HTML. Bearbeite sie im Quelltext, damit alle Inhalte erhalten bleiben.</p>}{source||unsupported?<textarea aria-label={`${label} – Markdown`} value={value} onChange={e=>onChange(e.target.value)} placeholder="Notiz in Markdown schreiben …"/>:<><div className="editor-toolbar" role="group" aria-label="Notiz formatieren"><select aria-label="Absatzformat" value={editor?.isActive('heading',{level:2})?'h2':editor?.isActive('heading',{level:3})?'h3':'p'} onChange={e=>{const chain=editor?.chain().focus();if(e.target.value==='p')chain?.setParagraph().run();else chain?.setHeading({level:e.target.value==='h2'?2:3}).run();}}><option value="p">Absatz</option><option value="h2">Überschrift</option><option value="h3">Unterüberschrift</option></select>{tools.map(([name,Icon,active,action])=><button key={name} type="button" className="icon-btn" aria-label={name} aria-pressed={editor?.isActive(active)||false} disabled={!editor} onClick={action}><Icon size={17}/></button>)}<button type="button" className="icon-btn" aria-label="Link bearbeiten" aria-pressed={editor?.isActive('link')||false} onClick={()=>{setUrl(editor?.getAttributes('link').href||'');setLinkOpen(!linkOpen);}}><Link size={17}/></button><button type="button" className="icon-btn" aria-label="Rückgängig" disabled={!editor?.can().undo()} onClick={()=>editor?.chain().focus().undo().run()}><Undo size={17}/></button><button type="button" className="icon-btn" aria-label="Wiederholen" disabled={!editor?.can().redo()} onClick={()=>editor?.chain().focus().redo().run()}><Redo size={17}/></button></div>{linkOpen&&<div className="editor-link"><label>Linkadresse<input type="url" value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://…"/></label><button type="button" className="secondary" disabled={!/^https?:\/\//i.test(url)} onClick={()=>{editor?.chain().focus().extendMarkRange('link').setLink({href:url}).run();setLinkOpen(false);}}>Link setzen</button><button type="button" className="text-btn" onClick={()=>{editor?.chain().focus().unsetLink().run();setLinkOpen(false);}}>Link entfernen</button></div>}<EditorContent editor={editor}/></>}</div>;
}
