import {useState,type CSSProperties} from 'react';
import Markdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import {HighlightedText} from './search-matches';
import {Minus,Plus,Type} from 'lucide-react';
export function plainToMarkdown(text:string){return text.replace(/\\/g,'\\\\').replace(/([`*_{}\[\]<>#!|~])/g,'\\$1').replace(/^(\s*)(\d+)\./gm,'$1$2\\.').replace(/^(\s*)[-+>]/gm,'$1\\$&');}
export function RichText({text,format='text',terms=[]}:{text:string;format?:string;terms?:string[]}){
 if(format!=='markdown')return <HighlightedText text={text} terms={terms}/>;
 const highlights=()=> (tree:any)=>{let count=0;const visit=(node:any)=>{if(!node.children)return;node.children=node.children.flatMap((child:any)=>{if(child.type!=='text'||!terms.length){visit(child);return [child];}const pattern=new RegExp([...terms].sort((a,b)=>b.length-a.length).map(t=>t.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')).join('|'),'giu');const result:any[]=[];let end=0;for(const hit of child.value.matchAll(pattern)){if(count++>=500)break;result.push({type:'text',value:child.value.slice(end,hit.index)},{type:'element',tagName:'mark',properties:{'data-search-hit':'',tabIndex:-1},children:[{type:'text',value:hit[0]}]});end=hit.index+hit[0].length;}result.push({type:'text',value:child.value.slice(end)});return result;});};visit(tree);};
 return <div className="markdown-body"><Markdown remarkPlugins={[remarkGfm]} rehypePlugins={[highlights]} skipHtml components={{img:({alt})=><span>[Bild: {alt||'ohne Beschreibung'}]</span>,a:({href,children})=><a href={href} target="_blank" rel="noopener noreferrer">{children}</a>}}>{text}</Markdown></div>;
}
const defaults={size:18,font:'serif'};
export function useReadingSettings(){const [value,setValue]=useState(()=>{try{const v=JSON.parse(localStorage.getItem('ablage-reading')||'null');return v&&[16,18,20,22,24].includes(v.size)&&['serif','sans'].includes(v.font)?v:defaults;}catch{return defaults;}});const update=(next:any)=>{setValue(next);try{localStorage.setItem('ablage-reading',JSON.stringify(next));}catch{}};return {value,update,style:{'--reading-size':value.size+'px','--reading-font':value.font==='sans'?'Barlow, sans-serif':'Georgia, serif'} as CSSProperties};}
export function ReadingControls({settings}:{settings:ReturnType<typeof useReadingSettings>}){const {value,update}=settings;return <details className="reading-controls"><summary><Type size={18}/>Lesedarstellung</summary><div><span>Schriftgröße · {value.size} px</span><button className="secondary" aria-label="Schrift verkleinern" disabled={value.size===16} onClick={()=>update({...value,size:value.size-2})}><Minus size={16}/></button><button className="secondary" aria-label="Schrift vergrößern" disabled={value.size===24} onClick={()=>update({...value,size:value.size+2})}><Plus size={16}/></button><label>Schriftart<select value={value.font} onChange={e=>update({...value,font:e.target.value})}><option value="serif">Serifenschrift · Georgia</option><option value="sans">Serifenlos · Barlow</option></select></label><button className="text-btn" onClick={()=>update(defaults)}>Zurücksetzen</button><small>Wird auf diesem Gerät gespeichert.</small></div></details>;}
