import {useEffect,useRef,useState,type RefObject} from 'react';
import {Search,Highlighter,ExternalLink,X} from 'lucide-react';
import {ReadingControls,useReadingSettings} from './reading';
import {SearchNavigation} from './search-matches';
export default function ReaderTools({clip,root,settings,terms,onTerms,onPage,onTarget,showMarks,onMarks,onCloseRef}:{clip:any;root:RefObject<HTMLElement|null>;settings:ReturnType<typeof useReadingSettings>;terms:string[];onTerms:(v:string[])=>void;onPage:(p:number)=>void;onTarget:(e:HTMLDivElement|null)=>void;showMarks:boolean;onMarks:(v:boolean)=>void;onCloseRef:RefObject<(()=>void)|null>}){
 const ref=useRef<HTMLDivElement>(null),[search,setSearch]=useState(false),[query,setQuery]=useState(terms.join(' '));
 const mobile=()=>window.matchMedia('(max-width:720px)').matches;
 function close(){if(!mobile())return;setSearch(false);onMarks(false);ref.current?.querySelectorAll<HTMLDetailsElement>('details[open]').forEach(d=>d.open=false);}
 function activate(which:string){if(!mobile())return;if(which!=='search')setSearch(false);if(which!=='marker')onMarks(false);ref.current?.querySelectorAll<HTMLDetailsElement>('details[open]').forEach(d=>{if(which==='font'&&d.classList.contains('reading-controls')||which==='source'&&d.classList.contains('shared-source-menu'))return;d.open=false;});}
 useEffect(()=>{onCloseRef.current=close;return()=>{onCloseRef.current=null;};});
 useEffect(()=>{setQuery(terms.join(' '));},[clip.id]);
 useEffect(()=>{const el=ref.current;if(!el)return;const measure=()=>{const bar=root.current?.querySelector('.reader-bar');if(bar)root.current?.style.setProperty('--reader-bar-height',bar.getBoundingClientRect().height+'px');const row=el.querySelector<HTMLElement>('.shared-tool-row'),panel=el.querySelector<HTMLElement>('.reading-controls[open]>div,.shared-source-menu[open] .shared-source-actions');row?.style.setProperty('--tool-panel-height',panel?panel.getBoundingClientRect().height+8+'px':'0px');};const observer=new ResizeObserver(measure);const bar=root.current?.querySelector('.reader-bar');if(bar)observer.observe(bar);measure();el.querySelectorAll('.reading-controls>div,.shared-source-actions').forEach(e=>observer.observe(e));el.addEventListener('toggle',measure,true);const outside=(e:PointerEvent)=>{const t=e.target as HTMLElement;if(!el.contains(t)&&!t.closest('.marker-floating,.marker-list'))close();};document.addEventListener('pointerdown',outside);return()=>{observer.disconnect();el.removeEventListener('toggle',measure,true);document.removeEventListener('pointerdown',outside);};},[]);
 return <div ref={ref} className="shared-statusbar backend-statusbar" role="region" aria-label="Lesewerkzeuge" onClick={e=>{if((e.target as HTMLElement).closest('.reading-controls button,.shared-source-menu a,.shared-marker-actions button,.search-navigation button'))close();}} onChange={e=>{if((e.target as HTMLElement).closest('.reading-controls'))close();}}><div className="shared-tool-row"><button className="text-btn" aria-expanded={search} onClick={()=>{activate('search');setSearch(!search);}}><Search size={18}/>{!search&&terms.length?'Suche aktiv':'Suchen'}</button><div className="shared-font-tool" onClick={e=>{if((e.target as HTMLElement).closest('summary'))activate('font');}}><ReadingControls settings={settings} label="Schrift"/></div><button className="text-btn" aria-pressed={showMarks} onClick={()=>{activate('marker');onMarks(!showMarks);}}><Highlighter size={18}/>Textmarker</button><details className="shared-source-menu" onClick={e=>{if((e.target as HTMLElement).closest('summary'))activate('source');}}><summary><ExternalLink size={18}/>Quelle</summary><div className="shared-source-actions">{clip.url&&<a className="source-link" href={clip.url} target="_blank" rel="noopener noreferrer">Original öffnen</a>}{clip.archive_key&&<a className="source-link" href={`/api/shared?id=${encodeURIComponent(clip.id)}&${clip.type==='pdf'?'pdf=1':'archive=1'}`} target="_blank" rel="noopener noreferrer">{clip.type==='pdf'?'Original-PDF öffnen':'Originalkopie öffnen'}</a>}</div></details></div>{search&&<div className="shared-find"><label className="sr-only" htmlFor="private-reader-search">Im Clip suchen</label><form onSubmit={e=>e.preventDefault()}><input id="private-reader-search" type="search" maxLength={200} placeholder="Im Clip suchen …" value={query} onChange={e=>{setQuery(e.target.value);onTerms(e.target.value.trim()?[e.target.value.trim()]:[]);}}/>{query&&<button type="button" className="icon-btn" aria-label="Suche löschen" onClick={()=>{setQuery('');onTerms([]);}}><X size={18}/></button>}</form><SearchNavigation root={root} terms={terms} clip={clip} onPage={onPage} autoJump={false} emptyLabel="Keine Treffer im Clip"/></div>}<div ref={onTarget} className="shared-marker-slot"/>{showMarks&&<p className="shared-marker-help">Text auswählen und markieren. Deine Markierungen werden nur in deinem Konto gespeichert.</p>}</div>;
}
