import {useEffect,useState,type RefObject} from 'react';
export function HighlightedText({text,terms}:{text:string;terms:string[]}){
 if(!terms.length)return <>{text}</>;
 const escaped=[...terms].sort((a,b)=>b.length-a.length).map(t=>t.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'));const pattern=new RegExp(escaped.join('|'),'giu');const nodes:any[]=[];let end=0,count=0;
 for(const hit of text.matchAll(pattern)){if(count++>=500)break;nodes.push(text.slice(end,hit.index));nodes.push(<mark data-search-hit key={hit.index} tabIndex={-1}>{hit[0]}</mark>);end=hit.index!+hit[0].length;}nodes.push(text.slice(end));return <>{nodes}</>;
}
export function SearchNavigation({root,terms,clip,onPage,autoJump=true,emptyLabel="Treffer in Quellenadresse oder Dokumentangaben"}:{root:RefObject<HTMLElement|null>;terms:string[];clip:any;onPage:(page:number)=>void;autoJump?:boolean;emptyLabel?:string}){
 useEffect(()=>{const el=root.current,bar=el?.querySelector('.reader-bar');if(!el||!bar)return;const update=()=>el.style.setProperty('--reader-bar-height',bar.getBoundingClientRect().height+'px');update();const observer=new ResizeObserver(update);observer.observe(bar);return()=>observer.disconnect();},[root]);
 const [active,setActive]=useState(0),[count,setCount]=useState(0),[pdfPage,setPdfPage]=useState<number|null>(null);
 const move=(index:number)=>{const marks=root.current?.querySelectorAll<HTMLElement>('[data-search-hit]');if(!marks?.length)return;index=Math.max(0,Math.min(index,marks.length-1));marks.forEach(m=>m.classList.remove('active-search-hit'));const mark=marks[index];mark.classList.add('active-search-hit');mark.focus({preventScroll:true});mark.scrollIntoView({block:'center',behavior:'auto'});setActive(index);let page:number|null=null;const body=mark.closest('.article-content');if(clip.type==='pdf'&&body){const range=document.createRange();range.selectNodeContents(body);range.setEndBefore(mark);const matches=[...range.toString().matchAll(/(?:^|\n)Seite (\d+)\n/g)];page=matches.length?Number(matches[matches.length-1][1]):null;}setPdfPage(page);if(page)onPage(page);};
 useEffect(()=>{setCount(root.current?.querySelectorAll('[data-search-hit]').length||0);setActive(0);if(terms.length&&autoJump)move(0);return()=>root.current?.querySelectorAll('[data-search-hit]').forEach(m=>m.classList.remove('active-search-hit'));},[clip,terms]);
 if(!terms.length)return null;
 return <nav className="search-navigation" aria-label="Fundstellen im Clip"><span role="status">{count?`Treffer ${active+1} von ${count}`:emptyLabel}</span>{count>0&&<><button className="secondary" disabled={active===0} onClick={()=>move(active-1)}>Vorheriger Treffer</button><button className="secondary" disabled={active===count-1} onClick={()=>move(active+1)}>Nächster Treffer</button></>}{pdfPage&&<button className="secondary" onClick={()=>{onPage(pdfPage);root.current?.querySelector('.pdf-viewer')?.scrollIntoView({block:'start'});}}>PDF-Seite {pdfPage} ansehen</button>}</nav>;
}
