import {useEffect,useRef,useState,useId,type ReactNode} from 'react';
import {createPortal} from 'react-dom';
import {Highlighter,X} from 'lucide-react';
import {locateMark,type TextMark} from './mark-anchor';
export default function TextMarker({clipId,section,local=false,csrf='',children,toolbarTarget,listOpen,onListToggle}:{clipId:string;section:'content'|'note';local?:boolean;csrf?:string;children:ReactNode;toolbarTarget?:HTMLElement|null;listOpen?:boolean;onListToggle?:(open:boolean)=>void}){
 const ref=useRef<HTMLDivElement>(null),name='ablage'+useId().replace(/[^a-z0-9]/gi,'');
 const [marks,setMarks]=useState<TextMark[]>([]),[selection,setSelection]=useState<Omit<TextMark,'id'>|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[loaded,setLoaded]=useState(false),[missing,setMissing]=useState<string[]>([]),[boxes,setBoxes]=useState<{left:number;top:number;width:number;height:number}[]>([]);
 const hitRanges=useRef<{id:string;range:Range}[]>([]),[clicked,setClicked]=useState<string|null>(null);
 const storageKey='ablage-marks-v1:'+clipId+':'+section;
 useEffect(()=>{let alive=true;setLoaded(false);setSelection(null);setClicked(null);setMarks([]);setError('');if(local){try{const raw=JSON.parse(localStorage.getItem(storageKey)||'[]');setMarks(Array.isArray(raw)?raw.filter(m=>m&&typeof m.id==='string'&&typeof m.quote==='string'&&typeof m.prefix==='string'&&typeof m.suffix==='string').slice(0,100):[]);setLoaded(true);}catch{setError('Markierungen konnten nicht geladen werden. Prüfe die Browserspeicherung.');}}else{const controller=new AbortController();fetch('/api/library?marks=1&id='+encodeURIComponent(clipId),{cache:'no-store',signal:controller.signal}).then(async r=>{const j=await r.json();if(!r.ok)throw Error(j.error);return j;}).then(j=>{if(alive){setMarks(j.marks.filter((m:TextMark)=>m.section===section));setLoaded(true);}}).catch(e=>{if(alive&&e.name!=='AbortError')setError(e.message);});return()=>{alive=false;controller.abort();};}return()=>{alive=false;};},[clipId,section,local,storageKey]);
 useEffect(()=>{const update=()=>{const root=ref.current,s=window.getSelection();if(!root||!s||s.isCollapsed||!s.rangeCount){setSelection(null);return;}const range=s.getRangeAt(0);if(!root.contains(range.startContainer)||!root.contains(range.endContainer)){setSelection(null);return;}const before=range.cloneRange();before.selectNodeContents(root);before.setEnd(range.startContainer,range.startOffset);const start=before.toString().length,quote=range.toString(),text=root.textContent||'';if(!quote.trim()||quote.length>2000){setSelection(null);return;}setSelection({section,quote,prefix:text.slice(Math.max(0,start-64),start),suffix:text.slice(start+quote.length,start+quote.length+64)});};document.addEventListener('selectionchange',update);return()=>document.removeEventListener('selectionchange',update);},[clipId,section]);
 useEffect(()=>{const clear=(e:PointerEvent)=>{const target=e.target as HTMLElement;if(!ref.current?.parentElement?.contains(target)&&!toolbarTarget?.contains(target)&&!target.closest('.marker-floating'))setClicked(null);};document.addEventListener('pointerdown',clear);return()=>document.removeEventListener('pointerdown',clear);},[toolbarTarget]);
 useEffect(()=>{const root=ref.current;if(!root)return;const api=(CSS as any).highlights,HighlightClass=(window as any).Highlight;
 const draw=()=>{const text=root.textContent||'',nodes:Text[]=[];const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);let n;while(n=walker.nextNode())nodes.push(n as Text);const ranges:Range[]=[],lost:string[]=[];hitRanges.current=[];
 const point=(offset:number)=>{let consumed=0;for(const node of nodes){if(offset<=consumed+node.length)return {node,offset:offset-consumed};consumed+=node.length;}return null;};
 for(const mark of marks){const at=locateMark(text,mark);if(!at){lost.push(mark.id);continue;}const a=point(at.start),b=point(at.end);if(a&&b){const range=document.createRange();range.setStart(a.node,a.offset);range.setEnd(b.node,b.offset);ranges.push(range);hitRanges.current.push({id:mark.id,range});}}
 setMissing(lost);if(api&&HighlightClass){api.set(name,new HighlightClass(...ranges));setBoxes([]);}else{const bounds=root.getBoundingClientRect();setBoxes(ranges.flatMap(r=>Array.from(r.getClientRects()).map(box=>({left:box.left-bounds.left,top:box.top-bounds.top,width:box.width,height:box.height}))));}};
 draw();const observer=new ResizeObserver(draw);observer.observe(root);window.addEventListener('resize',draw);return()=>{observer.disconnect();window.removeEventListener('resize',draw);api?.delete(name);};},[marks,children,name]);
 async function change(mark?:Omit<TextMark,'id'>,removeId?:string){if(!loaded||busy)return;setBusy(true);setError('');try{let next:TextMark[];if(local){if(mark&&marks.length>=100)throw Error('Maximal 100 Markierungen pro Textbereich.');next=removeId?marks.filter(m=>m.id!==removeId):[...marks,{...mark!,id:crypto.randomUUID()}];localStorage.setItem(storageKey,JSON.stringify(next));}else{const r=await fetch('/api/library',{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':csrf},body:JSON.stringify({action:removeId?'removeMark':'addMark',id:clipId,markId:removeId,...mark})});const j=await r.json();if(!r.ok)throw Error(j.error);next=removeId?marks.filter(m=>m.id!==removeId):[...marks,j.mark];}setMarks(next);setSelection(null);setClicked(null);window.getSelection()?.removeAllRanges();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <div className="text-marker">{loaded&&(selection||clicked)&&<button type="button" className="marker-floating" aria-label={selection?"Ausgewählten Text markieren":"Markierung entfernen"} title={selection?"Text markieren":"Markierung entfernen"} disabled={busy} onPointerDown={e=>e.preventDefault()} onClick={()=>selection?change(selection):clicked&&change(undefined,clicked)}>{selection?<Highlighter size={23} aria-hidden="true"/>:<X size={23} aria-hidden="true"/>}</button>}<style>{`::highlight(${name}){background:#ffe780;color:#202022}`}</style>{toolbarTarget?((selection||clicked)&&createPortal(<div className="shared-marker-actions">{selection&&<button type="button" className="secondary small" disabled={busy||!loaded} onPointerDown={e=>e.preventDefault()} onClick={()=>change(selection)}><Highlighter size={17}/>Markieren</button>}{clicked&&!selection&&<button type="button" className="secondary small" disabled={busy} onClick={()=>change(undefined,clicked)}><X size={17}/>Markierung entfernen</button>}</div>,toolbarTarget)):(<div className="marker-toolbar"><Highlighter size={17} aria-hidden="true"/><span>{local?'Dein Textmarker · nur in diesem Browser':'Dein Textmarker · nur für dich'}</span><button type="button" className="secondary small" disabled={!selection||busy||!loaded} onPointerDown={e=>e.preventDefault()} onClick={()=>selection&&change(selection)}>Markieren</button>{clicked&&<button type="button" className="text-btn" disabled={busy} onClick={()=>change(undefined,clicked)}>Markierung entfernen</button>}<small>Text auswählen, dann markieren · maximal 2.000 Zeichen.</small></div>)}{error&&<p className="error" role="alert">{error}</p>}<div className="marker-content" ref={ref} onClick={e=>{if(!window.getSelection()?.isCollapsed)return;const hit=hitRanges.current.find(h=>Array.from(h.range.getClientRects()).some(r=>e.clientX>=r.left&&e.clientX<=r.right&&e.clientY>=r.top&&e.clientY<=r.bottom));setClicked(hit?.id||null);if(hit)e.preventDefault();}}>{children}{boxes.length>0&&<div className="marker-overlay" aria-hidden="true">{boxes.map((box,i)=><span key={i} style={box}/>)}</div>}</div>{marks.length>0&&<details className="marker-list" open={listOpen} onToggle={e=>onListToggle?.(e.currentTarget.open)}><summary>Deine Markierungen · {marks.length}{missing.length>0&&` · ${missing.length} nicht zugeordnet`}</summary>{marks.map(mark=><div key={mark.id}><p>{mark.quote}{missing.includes(mark.id)&&<small>Diese Stelle ist nach einer Textänderung nicht mehr eindeutig zugeordnet.</small>}</p><button className="icon-btn" type="button" disabled={busy} aria-label={`Markierung entfernen: ${mark.quote.slice(0,50)}`} onClick={()=>change(undefined,mark.id)}><X size={17}/></button></div>)}</details>}</div>;
}
