CREATE TABLE IF NOT EXISTS members (email VARCHAR(190) PRIMARY KEY, name VARCHAR(100) NOT NULL, role VARCHAR(16) NOT NULL DEFAULT 'member', password_hash VARCHAR(255) NULL, created_at BIGINT NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS collections (id VARCHAR(36) PRIMARY KEY, name VARCHAR(100) NOT NULL, created_at BIGINT NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS clips (id VARCHAR(36) PRIMARY KEY, title VARCHAR(300) NOT NULL, url TEXT NOT NULL, type VARCHAR(16) NOT NULL, content MEDIUMTEXT NOT NULL, note MEDIUMTEXT NOT NULL, content_format VARCHAR(16) NOT NULL DEFAULT 'text', note_format VARCHAR(16) NOT NULL DEFAULT 'text', collection_id VARCHAR(36) NULL, author VARCHAR(190) NOT NULL, archive_key VARCHAR(40) NULL, created_at BIGINT NOT NULL, FOREIGN KEY (collection_id) REFERENCES collections(id), INDEX(collection_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS shares (id VARCHAR(36) PRIMARY KEY, hash CHAR(64) NOT NULL UNIQUE, target_id VARCHAR(36) NOT NULL, kind VARCHAR(16) NOT NULL, created_at BIGINT NOT NULL, expires_at BIGINT NULL, INDEX(target_id,kind)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS invitations (hash CHAR(64) PRIMARY KEY, email VARCHAR(190) NOT NULL, expires_at BIGINT NOT NULL, FOREIGN KEY (email) REFERENCES members(email) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS team_lock (id INTEGER PRIMARY KEY) ENGINE=InnoDB;
INSERT IGNORE INTO team_lock (id) VALUES (1);

CREATE TABLE IF NOT EXISTS clip_tags (clip_id VARCHAR(36) NOT NULL, tag VARCHAR(80) NOT NULL, PRIMARY KEY(clip_id,tag), INDEX(tag), FOREIGN KEY(clip_id) REFERENCES clips(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS clip_trash(clip_id VARCHAR(36) PRIMARY KEY,deleted_at BIGINT NOT NULL,deleted_by VARCHAR(190) NOT NULL,FOREIGN KEY(clip_id) REFERENCES clips(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS clip_favorites(clip_id VARCHAR(36) NOT NULL,member_email VARCHAR(190) NOT NULL,PRIMARY KEY(clip_id,member_email),FOREIGN KEY(clip_id) REFERENCES clips(id) ON DELETE CASCADE,FOREIGN KEY(member_email) REFERENCES members(email) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS saved_searches(id VARCHAR(36) PRIMARY KEY,member_email VARCHAR(190) NOT NULL,name VARCHAR(100) NOT NULL,params TEXT NOT NULL,created_at BIGINT NOT NULL,FOREIGN KEY(member_email) REFERENCES members(email) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS reader_marks (id VARCHAR(36) PRIMARY KEY,clip_id VARCHAR(36) NOT NULL,member_email VARCHAR(190) NOT NULL,section VARCHAR(16) NOT NULL,quote_text TEXT NOT NULL,prefix_text VARCHAR(64) NOT NULL,suffix_text VARCHAR(64) NOT NULL,created_at BIGINT NOT NULL,INDEX(clip_id,member_email)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
