const api=globalThis.browser||globalThis.chrome;
const canvas=document.getElementById('image'),ctx=canvas.getContext('2d'),status=document.getElementById('status');
const key='shot:'+new URL(location.href).searchParams.get('id');let original,clipSource,tool='crop',start,base;const history=[],annotations=[];
const snapshot=()=>{history.push({image:canvas.toDataURL(),annotations:[...annotations]});if(history.length>12)history.shift();document.getElementById('undo').disabled=false;};
const point=e=>{const r=canvas.getBoundingClientRect();return{x:Math.max(0,Math.min(canvas.width,(e.clientX-r.left)*canvas.width/r.width)),y:Math.max(0,Math.min(canvas.height,(e.clientY-r.top)*canvas.height/r.height))};};
const drawImage=src=>new Promise((resolve,reject)=>{const image=new Image();image.onload=()=>{if(image.width*image.height>16000000){reject(Error('Screenshot zu groß. Bitte mit kleinerem Browserfenster erneut erfassen.'));return;}canvas.width=image.width;canvas.height=image.height;ctx.drawImage(image,0,0);resolve(image);};image.onerror=()=>reject(Error('Screenshot konnte nicht geladen werden.'));image.src=src;});
function paint(a,b,preview=false){ctx.save();ctx.lineWidth=Math.max(3,canvas.width/350);ctx.strokeStyle='#b31229';if(tool==='highlight'){ctx.fillStyle='rgba(255,210,0,.32)';ctx.fillRect(Math.min(a.x,b.x),Math.min(a.y,b.y),Math.abs(b.x-a.x),Math.abs(b.y-a.y));}else if(tool==='arrow'){const angle=Math.atan2(b.y-a.y,b.x-a.x),size=ctx.lineWidth*5;ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.moveTo(b.x-size*Math.cos(angle-.5),b.y-size*Math.sin(angle-.5));ctx.lineTo(b.x,b.y);ctx.lineTo(b.x-size*Math.cos(angle+.5),b.y-size*Math.sin(angle+.5));ctx.stroke();}else if(tool==='crop'&&preview){ctx.setLineDash([8,5]);ctx.strokeRect(Math.min(a.x,b.x),Math.min(a.y,b.y),Math.abs(b.x-a.x),Math.abs(b.y-a.y));}ctx.restore();}
canvas.onpointerdown=e=>{if(!original)return;e.preventDefault();start=point(e);base=ctx.getImageData(0,0,canvas.width,canvas.height);canvas.setPointerCapture(e.pointerId);};
canvas.onpointermove=e=>{if(!start)return;ctx.putImageData(base,0,0);paint(start,point(e),true);};
canvas.onpointercancel=()=>{if(base)ctx.putImageData(base,0,0);start=null;};
canvas.onpointerup=e=>{if(!start)return;const a=start,b=point(e);start=null;ctx.putImageData(base,0,0);if(tool==='crop'){const x=Math.floor(Math.min(a.x,b.x)),y=Math.floor(Math.min(a.y,b.y)),w=Math.floor(Math.abs(b.x-a.x)),h=Math.floor(Math.abs(b.y-a.y));if(w<10||h<10){status.textContent='Bitte einen mindestens 10 × 10 Pixel großen Ausschnitt ziehen.';return;}snapshot();const pixels=ctx.getImageData(x,y,w,h);canvas.width=w;canvas.height=h;ctx.putImageData(pixels,0,0);}else if(tool==='text'){const text=document.getElementById('annotation').value.trim();if(!text){status.textContent='Bitte zuerst eine Anmerkung eingeben.';return;}snapshot();annotations.push(text);ctx.font=`600 ${Math.max(20,canvas.width/40)}px system-ui`;ctx.fillStyle='#b31229';ctx.fillText(text,b.x,b.y,Math.max(1,canvas.width-b.x));}else{snapshot();paint(a,b);}status.textContent='Bearbeitung übernommen. Rückgängig ist möglich.';};
for(const button of document.querySelectorAll('[data-tool]'))button.onclick=()=>{tool=button.dataset.tool;for(const b of document.querySelectorAll('[data-tool]'))b.setAttribute('aria-pressed',String(b===button));document.getElementById('text-field').hidden=tool!=='text';document.getElementById('instruction').textContent=tool==='text'?'Anmerkung eingeben und die Position im Bild antippen.':tool==='crop'?'Ziehe den gewünschten Ausschnitt.':'Ziehe im Bild, um eine Markierung hinzuzufügen.';};
document.getElementById('undo').onclick=async()=>{const item=history.pop();if(!item)return;await drawImage(item.image);annotations.splice(0,annotations.length,...item.annotations);document.getElementById('undo').disabled=!history.length;};
document.getElementById('reset').onclick=async()=>{if(!original)return;snapshot();await drawImage(original);annotations.length=0;};
document.getElementById('close').onclick=async()=>{await api.storage.local.remove(key);window.close();};
document.getElementById('send').onclick=async()=>{const button=document.getElementById('send');button.disabled=true;try{if(!clipSource)throw Error('Screenshot fehlt. Bitte erneut erfassen.');const image=canvas.toDataURL('image/jpeg',.85);if(image.length>4500000)throw Error('Das Bild ist zu groß. Wähle einen kleineren Ausschnitt.');const clip={...clipSource,type:'page',content:'Screenshot der sichtbaren Webseite.\n\n'+annotations.join('\n'),contentFormat:'text',note:'',archive:'<figure><img alt="Screenshot der Webseite" src="'+image+'"></figure>',captureQuality:{warnings:['Bildaufnahme: Der Bildinhalt ist ohne OCR nicht durchsuchbar. Anmerkungen werden als Text mitgespeichert.'],copiedImages:1,missingImages:0,mode:'screenshot'}};if(api.runtime.getManifest().name==='Die ABLAGE'){const reply=await api.runtime.sendNativeMessage('de.partei.hildesheim.ablage',{action:'queueCapture',clip});if(!reply?.ok)throw Error(reply?.error||'Übergabe fehlgeschlagen.');const link=document.getElementById('open');link.href=reply.launchURL;link.hidden=false;status.textContent='Bereit. In der App öffnen.';}else{const id=await AblageQueue.save(clip);const {libraryOrigin}=await api.storage.local.get('libraryOrigin');await api.tabs.create({url:libraryOrigin+'/?capture='+id});status.textContent='Entwurf in der Bibliothek geöffnet.';}await api.storage.local.remove(key);}catch(error){status.textContent=error.message;button.disabled=false;}};
(async()=>{try{const item=(await api.storage.local.get(key))[key];if(!item||Date.now()-item.createdAt>600000)throw Error('Screenshot abgelaufen. Bitte erneut erfassen.');original=item.image;clipSource={url:item.url,title:item.title.slice(0,300)};document.getElementById('source').textContent=new URL(item.url).hostname;const image=await drawImage(original);if(image.width*image.height>16000000)throw Error('Screenshot zu groß. Bitte mit kleinerem Browserfenster erneut erfassen.');}catch(error){status.textContent=error.message;document.getElementById('send').disabled=true;}})();

let keyboardPoint={x:20,y:30};
canvas.onkeydown=e=>{if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();const step=e.shiftKey?30:5;keyboardPoint.x=Math.max(0,Math.min(canvas.width,keyboardPoint.x+(e.key==='ArrowRight'?step:e.key==='ArrowLeft'?-step:0)));keyboardPoint.y=Math.max(0,Math.min(canvas.height,keyboardPoint.y+(e.key==='ArrowDown'?step:e.key==='ArrowUp'?-step:0)));if(start){ctx.putImageData(base,0,0);paint(start,keyboardPoint,true);}status.textContent=`Bildposition ${Math.round(keyboardPoint.x)}, ${Math.round(keyboardPoint.y)}. Enter setzt oder beendet die Auswahl.`;}else if(e.key==='Enter'){e.preventDefault();if(!start){start={...keyboardPoint};base=ctx.getImageData(0,0,canvas.width,canvas.height);if(tool!=='text')return;}const rect=canvas.getBoundingClientRect();canvas.onpointerup({clientX:rect.left+keyboardPoint.x*rect.width/canvas.width,clientY:rect.top+keyboardPoint.y*rect.height/canvas.height});}else if(e.key==='Escape'){e.preventDefault();canvas.onpointercancel();}else if((e.ctrlKey||e.metaKey)&&e.key==='z'){e.preventDefault();document.getElementById('undo').click();}};
